server:
  port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xyqdatabase?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root